#!/bin/sh
#Upstream makes use of “clknetsim” to test how well “chronyd” controls the
#system clocks in various conditions. Due to “clknetsim” not being available
#in Debian, let’s use autopkgtest facility to build it in a container and
#test “chronyd” from there.

set -e

testdir=test/simulation
clknetsim_dir=$testdir/clknetsim
clknetsim_ver=156b8e4
clknetsim_src=https://github.com/mlichvar/clknetsim/archive/${clknetsim_ver}/clknetsim-${clknetsim_ver}.tar.gz

# The simulation tests are only supported on Linux.
dpkg-architecture -ilinux-any || exit 0

prepare_clknetsim() {
    wget -q -P $clknetsim_dir $clknetsim_src && tar -xzf $clknetsim_dir/clknetsim-$clknetsim_ver.tar.gz \
        -C $clknetsim_dir --strip-components=1

    if [ ! -x "$clknetsim_dir/clknetsim" ] && [ ! -e "$clknetsim_dir/clknetsim.so" ]; then
        make -C $clknetsim_dir
    fi
}

run_test() {
    cd $testdir && ./run -i 20 -m 2
}

prepare_clknetsim && run_test
